# Generated by Django 5.2 on 2025-05-05 21:02
from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("api", "0001_initial"),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.AddField(
			model_name="stravauser",
			name="user",
			field=models.OneToOneField(
				help_text="Associated Django User",
				null=True,
				on_delete=django.db.models.deletion.CASCADE,
				related_name="strava_profile",
				to=settings.AUTH_USER_MODEL,
			),
		),
	]
