# Generated by Django 5.2 on 2025-05-10 12:30
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("api", "0003_alter_zonesummary_options_and_more"),
	]

	operations = [
		migrations.AlterField(
			model_name="zonesummary",
			name="zone_times_seconds",
			field=models.JSONField(
				default=dict,
				help_text=(
					"JSON containing aggregated time in seconds for each zone name for the period."
				),
			),
		),
	]
