# Generated by Django 5.2.2 on 2025-06-12 09:37
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models

import api.models


class Migration(migrations.Migration):
	dependencies = [
		("api", "0004_alter_zonesummary_zone_times_seconds"),
	]

	operations = [
		migrations.CreateModel(
			name="ActivityProcessingQueue",
			fields=[
				(
					"user",
					models.OneToOneField(
						on_delete=django.db.models.deletion.CASCADE,
						primary_key=True,
						related_name="activity_processing_queue",
						serialize=False,
						to="api.stravauser",
					),
				),
				(
					"last_processed_activity_start_time",
					models.DateTimeField(
						default=api.models.get_default_processing_start_time,
						help_text="The start time of the last successfully processed activity.",
					),
				),
				("created_at", models.DateTimeField(auto_now_add=True)),
				("updated_at", models.DateTimeField(auto_now=True)),
			],
			options={
				"verbose_name": "Activity Processing Queue",
				"verbose_name_plural": "Activity Processing Queues",
				"ordering": ["updated_at"],
			},
		),
	]
