# Generated by Django 5.2.2 on 2025-06-12 18:04
from __future__ import annotations

from django.db import migrations


def add_users_to_queue(apps, schema_editor):  # noqa: ARG001
	"""Add all existing StravaUser instances to the ActivityProcessingQueue."""
	StravaUser = apps.get_model("api", "StravaUser")
	ActivityProcessingQueue = apps.get_model("api", "ActivityProcessingQueue")

	# Get all existing users that don't have a queue entry
	users_without_queue = StravaUser.objects.exclude(activity_processing_queue__isnull=False)

	# Create queue entries for these users
	ActivityProcessingQueue.objects.bulk_create(
		[ActivityProcessingQueue(user=user) for user in users_without_queue]
	)


def remove_users_from_queue(apps, schema_editor):  # noqa: ARG001
	"""Remove all entries from the ActivityProcessingQueue (reverse operation)."""
	ActivityProcessingQueue = apps.get_model("api", "ActivityProcessingQueue")
	ActivityProcessingQueue.objects.all().delete()


class Migration(migrations.Migration):
	dependencies = [("api", "0005_activityprocessingqueue")]

	operations = [
		migrations.RunPython(add_users_to_queue, reverse_code=remove_users_from_queue),
	]
