# Generated by Django 5.2.3 on 2025-06-17 19:01
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [("api", "0006_add_existing_users_to_processing_queue")]

	operations = [
		migrations.AddField(
			model_name="activityprocessingqueue",
			name="num_processed",
			field=models.IntegerField(
				default=0, help_text="Number of activities processed so far."
			),
		),
		migrations.AddField(
			model_name="activityprocessingqueue",
			name="total_activities",
			field=models.IntegerField(
				blank=True, help_text="Total number of activities to sync for the user.", null=True
			),
		),
	]
