# Generated by Django 5.2 on 2025-05-07 20:34
from __future__ import annotations

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("api", "0002_stravauser_user"),
	]

	operations = [
		migrations.AlterModelOptions(
			name="zonesummary",
			options={
				"verbose_name": "Periodic Zone Summary",
				"verbose_name_plural": "Periodic Zone Summaries",
			},
		),
		migrations.AlterField(
			model_name="zonesummary",
			name="zone_times_seconds",
			field=models.JSONField(
				default=dict,
				help_text="Contains aggregated time in seconds for each zone name for the period.",
			),
		),
		migrations.CreateModel(
			name="ActivityZoneTimes",
			fields=[
				(
					"id",
					models.UUIDField(
						default=uuid.uuid4, editable=False, primary_key=True, serialize=False
					),
				),
				(
					"activity_id",
					models.BigIntegerField(db_index=True, help_text="Strava Activity ID"),
				),
				(
					"zone_name",
					models.CharField(
						help_text="Custom name of the heart rate zone", max_length=100
					),
				),
				(
					"duration_seconds",
					models.PositiveIntegerField(
						help_text="Time spent in this zone for this activity in seconds"
					),
				),
				(
					"activity_date",
					models.DateTimeField(
						default=django.utils.timezone.now,
						help_text="Date and time the activity started",
					),
				),
				("created_at", models.DateTimeField(auto_now_add=True)),
				("updated_at", models.DateTimeField(auto_now=True)),
				(
					"user",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="activity_zone_times",
						to="api.stravauser",
					),
				),
			],
			options={
				"verbose_name": "Activity Zone Time",
				"verbose_name_plural": "Activity Zone Times",
				"ordering": ["-activity_date", "user", "zone_name"],
				"indexes": [
					models.Index(
						fields=["user", "activity_id"], name="api_activit_user_id_0650d7_idx"
					),
					models.Index(
						fields=["user", "activity_date"], name="api_activit_user_id_83df2e_idx"
					),
				],
				"unique_together": {("user", "activity_id", "zone_name")},
			},
		),
	]
